### PR TITLE
Facade for all cached property variants

### PR DESCRIPTION
**Pull request by gsakkis**
This PR hides all the various cached property implementations behind a single `cachedproperty` callable, which is easier to read, write and extend with more options in the future. I picked this name instead of `cached_property` to avoid the potential backwards incompatibility (in case some code out there relies on it being a descriptor class instead of a function) and also to be similar to `staticmethod` and `classmethod` that don't use underscores either, but I don't mind renaming to something else if you prefer.

### CODE REVIEW

**Comment by pydanny** [comment]
I've looked at this a few times and am unsure about the name change. Later this week I'll ask others to weigh in on it.

Again, your code is really nice. :smile:

**Comment by pydanny** [comment]
I like it! Some considerations:

1. I am thinking `cached_property`should exist as an alias for `cachedproperty`, with a `warning.warn` style deprecation notice. The reason is  to keep a lot of code in the wild from breaking. I bring this up because, unfortunately, a lot of people include `cached-property` as an unpinned requirement. :(

2. In #21 I broach the idea of making the property **thread-safe** by default. If we go down this path, I think it should be applied to your changes.

**Comment by gsakkis** [comment]
1. If I understand correctly, aliasing `cached_property` to `cachedproperty` implies that what is now called `cached_property` should be renamed to, say, `single_threaded_cached_property`. Is this what you have in mind?
2. I don't think that the thread-safe version should be the default for a few reasons:
   - Multithreading is not very common in Python due to the GIL.
   - Many/most Python data structures and patterns are not thread safe, e.g. the simple augmented assignment operators.
   - It is slower than the unthreaded one.

    A clear note about thread safety in the docs is just fine IMO.

**Comment by pydanny** [comment]
Sorry for the long delay, I wasn't sure where to go with this one.

Upon reflection, I think switching the common name from  `cached_property` to `cachedproperty` is not the way to go. It violates PEP-8, which hurts my obsessive-compulsiveness. 

A better path would be to release a potentially backwards-incompatible change to the behavior of `cached_property` and release as a 2.0. However, a quick search reveals dozens of in-production projects that haven't pinned their dependencies. In theory that's not a problem of this library, but in practice that's a rude thing to do.

Finally, I agree with not making the library thread safe by default.

**Comment by pydanny** [comment]
Sadly, I am closing this pull request. However, I am open to having it run the other way, where `@cached_property` has an alias to `@cachedproperty`.

**Pull request closed without merging**
