### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by gsakkis**
- Fixed threaded_cached_property_with_ttl to actually be thread-safe.
- Allow the del statement for resetting cached properties with ttl instead of del obj._cache[attr].
- Overall code and test refactoring.

### CODE REVIEW

**Comment by gsakkis** [comment]
Heh looks like TravisCI uncovered a pypy bug.

**Comment by pydanny** [comment]
I love this pull request, I really do!  Do we know when the PyPy error fix will make it to a formal release?

**Comment by cfbolz** [comment]
As a workaround for the PyPy bug it would be possible to add a ``__set__`` method to the descriptor that then always raises the appropriate error. Then pypy would consider it to be a read write descriptor (but writing would still raise).

**Comment by gsakkis** [comment]
@pydanny thanks! I don't know when is PyPy's next release but I could add the ` __set__` method as @cfbolz suggested if you want to make Travis happy before merging.

**Comment by pydanny** [comment]
@gsakkis Adding the `__set__` method so we pass tests is good. I want to see Travis happy before I consider cutting a new release. :smile:

**Comment by gsakkis** [comment]
It turned out to be somewhat trickier. Before adding the `__delete__` method, all cached property variants were non-data descriptors, which happen to be settable implicitly. Now this could be inadvertent as intuitively cached properties shouldn't really be settable, so one could suggest to add a `__set__` that raises `AttributeError` to every class. However the implementation of `cached_property` and `threaded_cached_property` decorators relies on being non-data descriptors; they break if they get a `__set__` method.

So for the sake of consistency and backwards compatibility, I added a `__set__` to `cached_property_with_ttl` that explicitly allows setting instead of raising an error, so that all cached properties behave the same in this respect.

**Comment by gsakkis** [comment]
All tests pass at last! Btw I fixed `threaded_cached_property_with_ttl` to actually be thread-safe and refactored the tests to be reusable between the various cached property variants.

**Comment by pydanny** [comment]
I will probably cut a release tomorrow. Right now am working towards an epic Friday deadline.

**Comment by gsakkis** [comment]
Great, no rush. If you can wait for a day or two I have another feature PR in mind.

**Pull request merged**
